package com.myatejx.test.test_database.operate.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.myatejx.test.bean.TestEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_ENTITY".
*/
public class TestEntityDao extends AbstractDao<TestEntity, Long> {

    public static final String TABLENAME = "TEST_ENTITY";

    /**
     * Properties of entity TestEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Age = new Property(3, int.class, "age", false, "AGE");
        public final static Property TimeStamp = new Property(4, long.class, "timeStamp", false, "TIME_STAMP");
        public final static Property Lon = new Property(5, double.class, "lon", false, "LON");
        public final static Property Lat = new Property(6, double.class, "lat", false, "LAT");
        public final static Property Azimuth = new Property(7, int.class, "azimuth", false, "AZIMUTH");
        public final static Property Selected = new Property(8, boolean.class, "selected", false, "SELECTED");
    }


    public TestEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TestEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DATE\" TEXT," + // 2: date
                "\"AGE\" INTEGER  ," + // 3: age
                "\"TIME_STAMP\" INTEGER  ," + // 4: timeStamp
                "\"LON\" REAL  ," + // 5: lon
                "\"LAT\" REAL  ," + // 6: lat
                "\"AZIMUTH\" INTEGER  ," + // 7: azimuth
                "\"SELECTED\" INTEGER  );"); // 8: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
        stmt.bindLong(4, entity.getAge());
        stmt.bindLong(5, entity.getTimeStamp());
        stmt.bindDouble(6, entity.getLon());
        stmt.bindDouble(7, entity.getLat());
        stmt.bindLong(8, entity.getAzimuth());
        stmt.bindLong(9, entity.isSelected() ? 1: 0);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
        stmt.bindLong(4, entity.getAge());
        stmt.bindLong(5, entity.getTimeStamp());
        stmt.bindDouble(6, entity.getLon());
        stmt.bindDouble(7, entity.getLat());
        stmt.bindLong(8, entity.getAzimuth());
        stmt.bindLong(9, entity.isSelected() ? 1: 0);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestEntity readEntity(Cursor cursor, int offset) {
        TestEntity entity = new TestEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.getInt(offset + 3), // age
            cursor.getLong(offset + 4), // timeStamp
            cursor.getDouble(offset + 5), // lon
            cursor.getDouble(offset + 6), // lat
            cursor.getInt(offset + 7), // azimuth
            cursor.getShort(offset + 8) != 0 // selected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAge(cursor.getInt(offset + 3));
        entity.setTimeStamp(cursor.getLong(offset + 4));
        entity.setLon(cursor.getDouble(offset + 5));
        entity.setLat(cursor.getDouble(offset + 6));
        entity.setAzimuth(cursor.getInt(offset + 7));
        entity.setSelected(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
